from __future__ import annotations
import uuid
from backend.timeline.clips.baseClip import BaseClip


class webComp(BaseClip):
     

    CLIP_TYPE = "comp"

    def __init__(
        self,
        clipId: str = "",
        startFrame: int = 0,
        duration: int = 90,
        compId: str = "",
        mediaOffset: int = 0,
    ) -> None:
        super().__init__(
            clipId or str(uuid.uuid4()),
            startFrame,
            duration,
        )
        self.compId = compId
        self.mediaOffset = mediaOffset

    # Timeline helpers  

    def sourceFrame(self, timelineFrame: int) -> int:
        """Convert a timeline frame to the inner comp's local frame."""
        return max(0, (timelineFrame - self.startFrame) + self.mediaOffset)

    # BaseClip abstract implementations  
    def render(self, canvas, frame: int) -> None:
        """No-op: composition rendering is done by the C++ HeadlessCompositor."""
        pass

    def getThumbnail(self, frame: int, width: int = 160, height: int = 90) -> bytes:
        """Return empty bytes; comp thumbnails are not generated by Python."""
        return b""

    #   Serialization  
    def toDict(self) -> dict:
        return {
            "type": self.CLIP_TYPE,
            "clipId": self.clipId,
            "startFrame": self.startFrame,
            "duration": self.duration,
            "compId": self.compId,
            "mediaOffset": self.mediaOffset,
            "transform": self.transform.toDict(),
            "effects": [e.toDict() for e in self.effects],
        }

    @classmethod
    def fromDict(cls, data: dict) -> "CompClip":
        from backend.animation.transform import Transform
        c = cls(
            clipId=data["clipId"],
            startFrame=data["startFrame"],
            duration=data["duration"],
            compId=data.get("compId", ""),
            mediaOffset=data.get("mediaOffset", 0),
        )
        if "transform" in data:
            c.transform = Transform.fromDict(data["transform"])
        return c
